In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [4]:
# Exc 1

Mcol = 6
Mrow = 4

A = np.random.randn(Mrow, Mcol)
B = np.random.randn(Mrow, Mcol)

print(A)
print(' ')
print(B)

C = np.zeros(Mcol)

for i in range(Mcol):
    C[i] = np.dot(A[:,i], B[:,i])

print(' ')
print(C)

[[-1.02474148 -0.14595411 -1.84253244 -0.662343    0.91512199 -0.2234668 ]
 [-0.68911032  1.98888687 -1.71215722  0.86724019 -0.02991899 -2.00126589]
 [ 0.48674271 -1.88007676  0.41165277 -0.00237017 -1.66889213  0.48160445]
 [ 0.43846206 -0.7700509  -1.01055497  0.60344318 -1.04872013 -1.06065023]]
 
[[ 0.57657842 -0.10467874  1.27245712  0.22221381  1.01770458 -0.13249923]
 [ 0.34383436  0.67668519 -1.32134102 -0.51118783  0.34683523  1.90810457]
 [-1.33629345  0.66999704 -2.6069895   1.74324856  0.73457846 -2.29539481]
 [-0.58726478 -0.50916954  0.6535324   1.88414513 -1.12113757 -0.43027495]]
 
[-1.73570805  0.49356917 -1.8158048   0.54233835  0.87077421 -4.43811654]


In [10]:
# Exc 2

# Is the dot product commutative?

a = np.random.randn(100)
b = np.random.randn(100)

ab = np.dot(a, b)
ba = np.dot(b, a)
print(ab, ba, ab - ba)
print(' ')

v = [2,4]
w = [3,5]
print(np.dot(v,w), np.dot(w,v))

-4.581013895439129 -4.581013895439129 0.0
 
26 26
