In [1]:
import numpy as np

In [2]:
# NumPy

## Arrays

In [3]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [4]:
myMatrice = [[1,2,3], [4,5,6], [7,8,9]]
np.array(myMatrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [7]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(2,3)

array([[0.16234297, 0.0425707 , 0.08295585],
       [0.09645388, 0.06211934, 0.04908592]])

In [12]:
np.random.randn(2,3)

array([[ 1.20119221,  1.39511951, -1.30088385],
       [-0.15427366,  0.30910396,  0.28477018]])

In [13]:
np.random.randint(0,10,(2,3))

array([[3, 1, 6],
       [8, 1, 5]])

In [14]:
np.random.seed(42)
np.random.rand(4) #expected: [0.37454012, 0.95071431, 0.73199394, 0.59865848]

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [15]:
arr = np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [18]:
ranarr.max()

99

In [19]:
ranarr.min()

2

In [20]:
ranarr.argmax()

5

In [21]:
ranarr.argmin()

7

In [22]:
ranarr.dtype

dtype('int32')

In [23]:
arr.shape

(25,)

In [24]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [25]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [26]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [27]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[:5]

array([0, 1, 2, 3, 4])

In [30]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
arr = np.arange(0,11)

In [33]:
slice_arr = arr[:5]
slice_arr

array([0, 1, 2, 3, 4])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99])

In [36]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [37]:
arr = np.arange(0,11)
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_copy[:3] = 100
arr_copy

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_2d = np.array([np.arange(5,16,5), np.arange(20,31,5), np.arange(35,46,5)])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d.shape

(3, 3)

In [42]:
arr_2d[0]

array([ 5, 10, 15])

In [43]:
arr_2d[0,1]

10

In [44]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [48]:
arr = np.arange(1,11)
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [49]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])