In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales', axis=1)
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
poly_converter = PolynomialFeatures(degree=2, include_bias=False)
poly_converter.fit(X) # ploy_converter.fit_transform(X)

PolynomialFeatures(include_bias=False)

In [15]:
poly_features = poly_converter.transform(X) # 2nd degree polynomial features
poly_features

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [16]:
poly_features.shape

(200, 9)

In [17]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

In [19]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

[0, 1, 2]
230.1   => 2.301000e+02
37.8    => 3.780000e+01
69.2    => 6.920000e+01

[4, 5, 7]
230.1 * 37.8  => 8.697780e+03
230.1 * 69.2  => 1.592292e+04
37.8 * 69.2   => 2.615760e+03

[3, 6, 8]
230.1 **2    => 5.294601e+04
37.8 **2     => 1.428840e+03
69.2 **2     => 4.788640e+03

**Training the model and evaluating the performance**

In [24]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [28]:
model.fit(X_train, y_train)

LinearRegression()

In [29]:
test_predictions = model.predict(X_test)

In [31]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [33]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

**Polynomial Regression**
- MAE:    0.489
- MSE:    0.441
- RMSE:   0.664
- MAE + RMSE: -0.174

**Previous results using simple linear regression**
- MAE:    1.213
- MSE:    2.333
- RMSE:   1.516
- MAE + RMSE: -0.302

**Difference between the two models**
- MAE:    -0.724
- MSE:    -1.892
- RMSE:   -0.852
- MAE + RMSE: 0.128

In [34]:
MAE

0.4896798044803672

In [35]:
MSE

0.44175055104035066

In [36]:
RMSE

0.6646431757269089

In [37]:
MAE - RMSE

-0.1749633712465417

In [47]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [48]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

In [52]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])